[project]
name = "hdMerlin"
version = "0.9.0"

[requires]
platform = "cy2026"
profile = "core"

[build.intents.viewport-usd]
cache = {
  MERLIN_ENABLE_HYDRA2 = { type = "BOOL", value = true },
  MERLIN_BUILD_VIEWPORT = { type = "BOOL", value = true }
}
