# Validate the compiler output, not an assumed mapping of register classes.
file(READ "${MERLIN_METAL_SHADER_DIR}/gaussian.vertex.metal.reflection.json" _vertex)
file(READ "${MERLIN_METAL_SHADER_DIR}/gaussian.fragment.metal.reflection.json" _fragment)
function(require_json _json _expected)
  string(JSON _actual GET "${_json}" ${ARGN})
  if(NOT _actual STREQUAL "${_expected}")
    message(FATAL_ERROR "Gaussian ABI ${ARGN}: expected ${_expected}, got ${_actual}")
  endif()
endfunction()
require_json("${_vertex}" gaussian_metal_vertex entryPoints 0 name)
require_json("${_vertex}" vertex entryPoints 0 stage)
require_json("${_vertex}" gaussian_instances parameters 0 name)
require_json("${_vertex}" byteAddressBuffer parameters 0 type baseShape)
require_json("${_vertex}" constantBuffer parameters 0 bindings 0 kind)
require_json("${_vertex}" 0 parameters 0 bindings 0 index)
require_json("${_vertex}" gaussian_constants parameters 1 name)
require_json("${_vertex}" constantBuffer parameters 1 binding kind)
require_json("${_vertex}" 1 parameters 1 binding index)
require_json("${_vertex}" 8 parameters 1 type elementVarLayout binding size)
require_json("${_vertex}" inverse_extent parameters 1 type elementType fields 0 name)
require_json("${_vertex}" 0 parameters 1 type elementType fields 0 binding offset)
require_json("${_vertex}" 2 parameters 1 type elementType fields 0 type elementCount)
require_json("${_fragment}" gaussian_metal_fragment entryPoints 0 name)
require_json("${_fragment}" fragment entryPoints 0 stage)
foreach(_index RANGE 0 2)
  require_json("${_fragment}" "${_index}"
    entryPoints 0 result type fields ${_index} binding index)
  require_json("${_fragment}" SV_TARGET
    entryPoints 0 result type fields ${_index} semanticName)
endforeach()
require_json("${_fragment}" float32 entryPoints 0 result type fields 0 type elementType scalarType)
require_json("${_fragment}" uint32 entryPoints 0 result type fields 1 type scalarType)
require_json("${_fragment}" uint32 entryPoints 0 result type fields 2 type scalarType)
# Reflection and the emitted MSL must agree on Metal's single buffer namespace.
file(READ "${MERLIN_METAL_SHADER_DIR}/gaussian.vertex.metal" _msl)
foreach(_binding "gaussian_instances_[0-9]+ \\[\\[buffer\\(0\\)\\]\\]"
                 "gaussian_constants_[0-9]+ \\[\\[buffer\\(1\\)\\]\\]")
  if(NOT _msl MATCHES "${_binding}")
    message(FATAL_ERROR "Generated Metal binding is missing: ${_binding}")
  endif()
endforeach()
