# Project identity and dependency compatibility policy.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_SOURCE_DIR}/VERSION")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" MERLIN_PROJECT_VERSION)
string(STRIP "${MERLIN_PROJECT_VERSION}" MERLIN_PROJECT_VERSION)
if(NOT MERLIN_PROJECT_VERSION MATCHES
   "^[0-9]+[.][0-9]+[.][0-9]+$")
  message(FATAL_ERROR
    "VERSION must contain exactly one stable SemVer value (MAJOR.MINOR.PATCH)")
endif()

set(MERLIN_VULKAN_MIN_VERSION_MAJOR 1)
set(MERLIN_VULKAN_MIN_VERSION_MINOR 4)
set(MERLIN_VULKAN_MIN_VERSION
    "${MERLIN_VULKAN_MIN_VERSION_MAJOR}.${MERLIN_VULKAN_MIN_VERSION_MINOR}")
set(MERLIN_OPENUSD_VALIDATED_VERSIONS "26.05;26.08")
set(MERLIN_OPENUSD_VALIDATED_VERSION "26.05")
set(MERLIN_SLANG_REQUIRED_SERIES "2026.8")
set(MERLIN_SHADER_ARTIFACT_SCHEMA_VERSION 2)
set(MERLIN_SHADER_ABI_VERSION 10)
# Identity schemas defined by merlin/core/shader_artifact.hpp. The shader
# manifest is generated against these, so a formula change is a schema change.
set(MERLIN_SHADER_MODULE_IDENTITY_SCHEMA "merlin.shader-module-identity/v1")
set(MERLIN_SHADER_ARTIFACT_KEY_SCHEMA "merlin.shader-artifact-key/v1")
set(MERLIN_MATERIALX_MIN_VERSION "1.39.6")
set(MERLIN_MATERIALX_GENSLANG_REVISION
    "38368ee04da84ce1f8837ecba7322dd6d81291f8")
set(MERLIN_GLFW_MIN_VERSION "3.4")
set(MERLIN_GLFW_PINNED_COMMIT
    "7b6aead9fb88b3623e3b3725ebb42670cbe4c579")
set(MERLIN_IMGUI_VERSION "1.92.8")
set(MERLIN_IMGUI_PINNED_COMMIT
    "8936b58fe26e8c3da834b8f60b06511d537b4c63")
set(MERLIN_NFD_VERSION "1.3.0")
set(MERLIN_NFD_PINNED_COMMIT
    "3cd252a8f7ca32419b1ca235c2990ba6a0ecba7c")
